package com.arcologydesigns.Views;

import com.arcologydesigns.Controllers.AuthenticationController;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;

/**
 * Authentication created by Borislav S. on 7/8/2015 @ 9:44 PM.
 */
public class AuthenticationForm extends JFrame {
   private JPanel authenticationPanel;
   private JTextField usernameTextField;
   private JPasswordField passwordTextField;
   private JButton loginButton;
   private JButton requestIDButton;
   private ImageIcon img = null;

   public AuthenticationForm() {
      createAndShowGUI();
      addButtonEventListeners();
   }

   /**
    * Creates a form with a background image and a semi-transparent overlay for displaying login content
    */
   private void createAndShowGUI() {

      // Set title and default close operation
      setTitle("User Authentication");
      setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

      // Set a background for JFrame
      ClassLoader cldr = this.getClass().getClassLoader();
      URL imageURL = cldr.getResource("images/desert.jpg");

      assert imageURL != null;  //used during debugging

      if (imageURL != null) {
         img = new ImageIcon(imageURL);
      }
      setContentPane(new JLabel(img));

      /*
         EXAMPLE OF BAD CODE: the below code. To fetch a resource, use the absolute reference path and invoke
         getClassLoader() then getResource() to set a resource. Otherwise, the resource will not show when running
         the application from a JAR file.

            setContentPane(new JLabel(new ImageIcon(".\\resources\\desert.jpg")));
      */

      // Set some layout, say FlowLayout
      setLayout(new FlowLayout());

      // Set the background, black with 125 as alpha value
      // This is less transparent
      authenticationPanel.setBackground(new Color(0, 0, 0, 125));

      // Set some size to the panels
      authenticationPanel.setPreferredSize(new Dimension(500, 300));
      //p2.setPreferredSize(new Dimension(250,150));

      // Add the panels to the JFrame
      add(authenticationPanel);
      //add(p2);

      // Set the size of the JFrame and make it visible
      setSize(600, 400);
      setVisible(true);
   } // end createAndShowGUI()

   private void addButtonEventListeners() {
      requestIDButton.addActionListener(new ActionListener() {
         @Override
         public void actionPerformed(ActionEvent actionEvent) {
            EmailForm e = new EmailForm("Request a user ID");
            e.setSize(700, 400);
            setVisible(false);
         }
      });

      loginButton.addActionListener(new ActionListener() {
         @Override
         public void actionPerformed(ActionEvent actionEvent) {
            AuthenticationController authenticate = new AuthenticationController();
            boolean isUserValid = authenticate.authenticateUser(getUsernameTextField(), getPasswordTextField());

            if (isUserValid) {
               char userType = authenticate.getUserType();

               EducatorMainForm educator = new EducatorMainForm(userType);
               educator.setUserIdLabel(getUsernameTextField());

               setVisible(false);
            } else {
               JOptionPane.showMessageDialog(getParent(),
                       "Invalid user ID or password!\nPlease try again or submit an access request.",
                       "Authentication Error!",
                       JOptionPane.ERROR_MESSAGE);
            }
         }
      });
   } // end addButtonListeners()

   public static void main() {
      // Run in the Event Dispatch Thread (EDT)
      SwingUtilities.invokeLater(new Runnable() {
         public void run() {
            new AuthenticationForm();
         }
      });
   } // end main()

   public char[] getPasswordTextField() {
      return passwordTextField.getPassword();
   }

   public String getUsernameTextField() {
      return usernameTextField.getText();
   }

   {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
      $$$setupUI$$$();
   }

   /**
    * Method generated by IntelliJ IDEA GUI Designer
    * >>> IMPORTANT!! <<<
    * DO NOT edit this method OR call it in your code!
    *
    * @noinspection ALL
    */
   private void $$$setupUI$$$() {
      authenticationPanel = new JPanel();
      authenticationPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(12, 9, new Insets(0, 0, 0, 0), -1, -1));
      authenticationPanel.setBackground(new Color(-16562316));
      final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
      authenticationPanel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 7, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, new Dimension(-1, 10), new Dimension(-1, 10), null, 0, false));
      final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
      authenticationPanel.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(11, 0, 1, 9, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, new Dimension(-1, 10), new Dimension(-1, 10), null, 0, false));
      final com.intellij.uiDesigner.core.Spacer spacer3 = new com.intellij.uiDesigner.core.Spacer();
      authenticationPanel.add(spacer3, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 11, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(10, -1), new Dimension(10, -1), null, 0, false));
      final com.intellij.uiDesigner.core.Spacer spacer4 = new com.intellij.uiDesigner.core.Spacer();
      authenticationPanel.add(spacer4, new com.intellij.uiDesigner.core.GridConstraints(0, 8, 11, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(10, -1), new Dimension(10, -1), null, 0, false));
      final JLabel label1 = new JLabel();
      label1.setFont(new Font(label1.getFont().getName(), Font.BOLD, 48));
      label1.setForeground(new Color(-1));
      label1.setText("Login Required");
      authenticationPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 7, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final com.intellij.uiDesigner.core.Spacer spacer5 = new com.intellij.uiDesigner.core.Spacer();
      authenticationPanel.add(spacer5, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 2, 7, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, new Dimension(80, -1), new Dimension(80, -1), null, 0, false));
      final com.intellij.uiDesigner.core.Spacer spacer6 = new com.intellij.uiDesigner.core.Spacer();
      authenticationPanel.add(spacer6, new com.intellij.uiDesigner.core.GridConstraints(4, 7, 6, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      loginButton = new JButton();
      loginButton.setText("Login");
      authenticationPanel.add(loginButton, new com.intellij.uiDesigner.core.GridConstraints(8, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(100, -1), new Dimension(100, -1), null, 0, false));
      final com.intellij.uiDesigner.core.Spacer spacer7 = new com.intellij.uiDesigner.core.Spacer();
      authenticationPanel.add(spacer7, new com.intellij.uiDesigner.core.GridConstraints(9, 1, 1, 5, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      final com.intellij.uiDesigner.core.Spacer spacer8 = new com.intellij.uiDesigner.core.Spacer();
      authenticationPanel.add(spacer8, new com.intellij.uiDesigner.core.GridConstraints(8, 5, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, new Dimension(25, -1), new Dimension(25, -1), new Dimension(25, -1), 0, false));
      requestIDButton = new JButton();
      requestIDButton.setText("Request ID");
      authenticationPanel.add(requestIDButton, new com.intellij.uiDesigner.core.GridConstraints(8, 3, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(100, -1), new Dimension(100, -1), null, 0, false));
      final com.intellij.uiDesigner.core.Spacer spacer9 = new com.intellij.uiDesigner.core.Spacer();
      authenticationPanel.add(spacer9, new com.intellij.uiDesigner.core.GridConstraints(7, 1, 1, 6, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(-1, 15), new Dimension(-1, 15), 0, false));
      final JLabel label2 = new JLabel();
      label2.setFont(new Font(label2.getFont().getName(), Font.BOLD, 26));
      label2.setForeground(new Color(-1));
      label2.setText("Password: ");
      authenticationPanel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(5, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final JLabel label3 = new JLabel();
      label3.setFont(new Font(label3.getFont().getName(), Font.BOLD, 26));
      label3.setForeground(new Color(-1));
      label3.setText("Username: ");
      authenticationPanel.add(label3, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_SOUTH, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      usernameTextField = new JTextField();
      authenticationPanel.add(usernameTextField, new com.intellij.uiDesigner.core.GridConstraints(4, 2, 1, 4, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(210, -1), null, 0, false));
      passwordTextField = new JPasswordField();
      authenticationPanel.add(passwordTextField, new com.intellij.uiDesigner.core.GridConstraints(5, 2, 1, 4, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(210, -1), null, 0, false));
      label2.setLabelFor(passwordTextField);
      label3.setLabelFor(usernameTextField);
   }

   /**
    * @noinspection ALL
    */
   public JComponent $$$getRootComponent$$$() {
      return authenticationPanel;
   }
} // end class AuthenticationForm
