package com.arcologydesigns.Views;

import com.arcologydesigns.emailService.Mail;

import javax.mail.MessagingException;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import static java.lang.System.*;

/**
 * Test created by Borislav S. on 7/3/2015 @ 5:53 PM.
 */
public class EmailForm extends JFrame {
   private JPanel emailPanel;
   private JLabel emailLabel;
   private JButton sendEmailButton;
   private JTextArea messageTextArea;
   private JLabel emailBodyLabel;
   private JTextField ccTextField;
   private JTextField toTextField;
   private JTextField subjectTextField;

   public EmailForm(String formTitle) {

      super(formTitle);
      setContentPane(emailPanel);
      pack();
      setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

      toTextField.setText("-");
      ccTextField.setText("-");
      subjectTextField.setText("-");
      messageTextArea.setText("-");

      sendEmailButton.addActionListener(new ActionListener() {
         @Override
         public void actionPerformed(ActionEvent actionEvent) {

            try {
               Mail.generateAndSendEmail(getToTextField(), getCcTextField(), getSubjectTextField(), getMessageTextArea());

               out.println("\n\n ===> Your Java Program just sent an email successfully. Check your email...");
            } catch (MessagingException e) {
               out.printf("Messaging exception: %s", e);
            }
         }
      });

      setVisible(true);

   } // end EmailForm constructor

   public String getToTextField() {
      return toTextField.getText();
   }

   public String getMessageTextArea() {
      return messageTextArea.getText();
   }

   public String getCcTextField() {
      return ccTextField.getText();
   }

   public String getSubjectTextField() {
      return subjectTextField.getText();
   }

   public void setMessageText(String messageText) {
      this.messageTextArea.setText(messageText);
   }

   public void setCcTextField(String ccText) {
      this.ccTextField.setText(ccText);
   }

   public void setToText(String toText) {
      this.toTextField.setText(toText);
   }

   public void setSubjectText(String subjectText) {
      this.subjectTextField.setText(subjectText);
   }

   {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
      $$$setupUI$$$();
   }

   /**
    * Method generated by IntelliJ IDEA GUI Designer
    * >>> IMPORTANT!! <<<
    * DO NOT edit this method OR call it in your code!
    *
    * @noinspection ALL
    */
   private void $$$setupUI$$$() {
      emailPanel = new JPanel();
      emailPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(8, 4, new Insets(15, 15, 15, 15), -1, -1));
      emailPanel.setBackground(new Color(-14596236));
      emailPanel.setEnabled(true);
      emailPanel.putClientProperty("html.disable", Boolean.FALSE);
      final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
      emailPanel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(1, 3, 7, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      emailLabel = new JLabel();
      emailLabel.setBackground(new Color(-1180161));
      emailLabel.setEnabled(true);
      emailLabel.setFont(new Font(emailLabel.getFont().getName(), Font.BOLD, 14));
      emailLabel.setForeground(new Color(-1));
      emailLabel.setText("SMTP EMAIL FORM");
      emailPanel.add(emailLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 4, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      sendEmailButton = new JButton();
      sendEmailButton.setEnabled(true);
      sendEmailButton.setFont(new Font(sendEmailButton.getFont().getName(), sendEmailButton.getFont().getStyle(), 14));
      sendEmailButton.setText("Send Email");
      emailPanel.add(sendEmailButton, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 7, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_SOUTHEAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 25), new Dimension(150, 25), 0, false));
      messageTextArea = new JTextArea();
      emailPanel.add(messageTextArea, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(350, 200), new Dimension(350, 200), 0, false));
      final JLabel label1 = new JLabel();
      label1.setFont(new Font(label1.getFont().getName(), Font.BOLD, 14));
      label1.setForeground(new Color(-1));
      label1.setText("TO:");
      emailPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final JLabel label2 = new JLabel();
      label2.setFont(new Font(label2.getFont().getName(), Font.BOLD, 14));
      label2.setForeground(new Color(-1));
      label2.setText("CC:");
      emailPanel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      ccTextField = new JTextField();
      emailPanel.add(ccTextField, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
      toTextField = new JTextField();
      emailPanel.add(toTextField, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
      final JLabel label3 = new JLabel();
      label3.setFont(new Font(label3.getFont().getName(), Font.BOLD, 14));
      label3.setForeground(new Color(-1));
      label3.setText("Subject:");
      emailPanel.add(label3, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      subjectTextField = new JTextField();
      emailPanel.add(subjectTextField, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
      emailBodyLabel = new JLabel();
      emailBodyLabel.setFont(new Font(emailBodyLabel.getFont().getName(), Font.BOLD, 14));
      emailBodyLabel.setForeground(new Color(-1));
      emailBodyLabel.setText("Message Body: ");
      emailPanel.add(emailBodyLabel, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 4, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final JSeparator separator1 = new JSeparator();
      separator1.setBackground(new Color(-14596236));
      separator1.setEnabled(false);
      separator1.setForeground(new Color(-14596236));
      emailPanel.add(separator1, new com.intellij.uiDesigner.core.GridConstraints(6, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
   }

   /**
    * @noinspection ALL
    */
   public JComponent $$$getRootComponent$$$() {
      return emailPanel;
   }
} // end class EmailForm
