package com.arcologydesigns.Views;

import javax.swing.*;
import java.awt.*;

/**
 * InstructorInfoForm created by Borislav S. on 7/14/2015 @ 7:22 PM.
 */
public class InstructorInfoForm extends JDialog {


   private JPanel instructorInfoPanel;

   {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
      $$$setupUI$$$();
   }

   /**
    * Method generated by IntelliJ IDEA GUI Designer
    * >>> IMPORTANT!! <<<
    * DO NOT edit this method OR call it in your code!
    *
    * @noinspection ALL
    */
   private void $$$setupUI$$$() {
      instructorInfoPanel = new JPanel();
      instructorInfoPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
      instructorInfoPanel.setBackground(new Color(-14596236));
   }

   /**
    * @noinspection ALL
    */
   public JComponent $$$getRootComponent$$$() {
      return instructorInfoPanel;
   }
}
