package com.arcologydesigns.Views;

import javax.swing.*;
import java.awt.*;

/**
 * StudentAnalyticsReportForm created by Borislav S. on 7/14/2015 @ 7:24 PM.
 */
public class StudentAnalyticsReportForm extends JDialog {
   private JPanel studentAnalyticsPanel;

   {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
      $$$setupUI$$$();
   }

   /**
    * Method generated by IntelliJ IDEA GUI Designer
    * >>> IMPORTANT!! <<<
    * DO NOT edit this method OR call it in your code!
    *
    * @noinspection ALL
    */
   private void $$$setupUI$$$() {
      studentAnalyticsPanel = new JPanel();
      studentAnalyticsPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
      studentAnalyticsPanel.setBackground(new Color(-14596236));
   }

   /**
    * @noinspection ALL
    */
   public JComponent $$$getRootComponent$$$() {
      return studentAnalyticsPanel;
   }
}
