package com.arcologydesigns.Views;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by bss64 on 7/14/2015.
 * edited by arnissim on 7/28/2015
 */

public class StudentInfoForm extends JDialog {
   private JPanel studentInfoPanel;
   private JLabel studentNameLabel;
   private JLabel studentPhone;
   private JLabel studentID;
   private JLabel studentAddress;
   private JLabel studentEmail;
   private JButton emailStudentButton;

   public StudentInfoForm() {
      createGUI();
      setActionListeners();
   }

   private void createGUI() {
      // Set title and default close operation
      setTitle("Student Information");
      setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);


      // Add the panels to the JFrame
      add(studentInfoPanel);

      // Set the size of the JFrame and make it visible
      setSize(600, 400);
      setVisible(true);
   }

   private void setActionListeners() {
      emailStudentButton.addActionListener(new ActionListener() {
         @Override
         public void actionPerformed(ActionEvent e) {
            EmailForm emailStudentForm = new EmailForm("Email " + getStudentNameLabel());
            emailStudentForm.setToText(getStudentEmail());

         }
      });
   }

   public void setStudentNameLabel(String studentNameLabel) {
      this.studentNameLabel.setText(studentNameLabel);
   }

   public void setStudentPhone(String studentPhone) {
      this.studentPhone.setText(studentPhone);
   }

   public void setStudentID(String studentID) {
      this.studentID.setText(studentID);
   }

   public void setStudentAddress(String studentAddress) {
      this.studentAddress.setText(studentAddress);
   }

   public void setStudentEmail(String studentEmail) {
      this.studentEmail.setText(studentEmail);
   }

   public String getStudentEmail() {
      return studentEmail.getText();
   }

   public String getStudentAddress() {
      return studentAddress.getText();
   }

   public String getStudentID() {
      return studentID.getText();
   }

   public String getStudentPhone() {
      return studentPhone.getText();
   }

   public String getStudentNameLabel() {
      return studentNameLabel.getText();
   }

   {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
      $$$setupUI$$$();
   }

   /**
    * Method generated by IntelliJ IDEA GUI Designer
    * >>> IMPORTANT!! <<<
    * DO NOT edit this method OR call it in your code!
    *
    * @noinspection ALL
    */
   private void $$$setupUI$$$() {
      studentInfoPanel = new JPanel();
      studentInfoPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(10, 8, new Insets(0, 0, 0, 0), -1, -1));
      studentInfoPanel.setBackground(new Color(-14596236));
      studentInfoPanel.setFont(new Font(studentInfoPanel.getFont().getName(), Font.BOLD, 18));
      studentInfoPanel.setForeground(new Color(-1));
      final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
      studentInfoPanel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 5, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
      final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
      studentInfoPanel.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 8, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      final com.intellij.uiDesigner.core.Spacer spacer3 = new com.intellij.uiDesigner.core.Spacer();
      studentInfoPanel.add(spacer3, new com.intellij.uiDesigner.core.GridConstraints(9, 2, 1, 5, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
      final com.intellij.uiDesigner.core.Spacer spacer4 = new com.intellij.uiDesigner.core.Spacer();
      studentInfoPanel.add(spacer4, new com.intellij.uiDesigner.core.GridConstraints(1, 7, 8, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      studentNameLabel = new JLabel();
      studentNameLabel.setBackground(new Color(-1));
      studentNameLabel.setFont(new Font(studentNameLabel.getFont().getName(), Font.BOLD, 24));
      studentNameLabel.setForeground(new Color(-1));
      studentNameLabel.setText("Student Name");
      studentInfoPanel.add(studentNameLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 1, 5, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      studentAddress = new JLabel();
      studentAddress.setBackground(new Color(-1));
      studentAddress.setFont(new Font(studentAddress.getFont().getName(), Font.BOLD, 18));
      studentAddress.setForeground(new Color(-1));
      studentAddress.setText("StudentAddress");
      studentInfoPanel.add(studentAddress, new com.intellij.uiDesigner.core.GridConstraints(5, 2, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final com.intellij.uiDesigner.core.Spacer spacer5 = new com.intellij.uiDesigner.core.Spacer();
      studentInfoPanel.add(spacer5, new com.intellij.uiDesigner.core.GridConstraints(7, 2, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      studentID = new JLabel();
      studentID.setBackground(new Color(-1));
      studentID.setFont(new Font(studentID.getFont().getName(), Font.BOLD, 18));
      studentID.setForeground(new Color(-1));
      studentID.setText("StudentID");
      studentInfoPanel.add(studentID, new com.intellij.uiDesigner.core.GridConstraints(3, 2, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      studentPhone = new JLabel();
      studentPhone.setBackground(new Color(-1));
      studentPhone.setFont(new Font(studentPhone.getFont().getName(), Font.BOLD, 18));
      studentPhone.setForeground(new Color(-1));
      studentPhone.setText("StudentPhone");
      studentInfoPanel.add(studentPhone, new com.intellij.uiDesigner.core.GridConstraints(4, 2, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      studentEmail = new JLabel();
      studentEmail.setBackground(new Color(-1));
      studentEmail.setFont(new Font(studentEmail.getFont().getName(), Font.BOLD, 18));
      studentEmail.setForeground(new Color(-1));
      studentEmail.setText("StudentEmail");
      studentInfoPanel.add(studentEmail, new com.intellij.uiDesigner.core.GridConstraints(6, 2, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final com.intellij.uiDesigner.core.Spacer spacer6 = new com.intellij.uiDesigner.core.Spacer();
      studentInfoPanel.add(spacer6, new com.intellij.uiDesigner.core.GridConstraints(2, 2, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      final JLabel label1 = new JLabel();
      label1.setFont(new Font(label1.getFont().getName(), label1.getFont().getStyle(), 14));
      label1.setForeground(new Color(-1));
      label1.setText("Student ID: ");
      studentInfoPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final JLabel label2 = new JLabel();
      label2.setFont(new Font(label2.getFont().getName(), label2.getFont().getStyle(), 14));
      label2.setForeground(new Color(-1));
      label2.setText("Phone: ");
      studentInfoPanel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final JLabel label3 = new JLabel();
      label3.setFont(new Font(label3.getFont().getName(), label3.getFont().getStyle(), 14));
      label3.setForeground(new Color(-1));
      label3.setText("Mailing Address: ");
      studentInfoPanel.add(label3, new com.intellij.uiDesigner.core.GridConstraints(5, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final JLabel label4 = new JLabel();
      label4.setFont(new Font(label4.getFont().getName(), label4.getFont().getStyle(), 14));
      label4.setForeground(new Color(-1));
      label4.setText("Email:");
      studentInfoPanel.add(label4, new com.intellij.uiDesigner.core.GridConstraints(6, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      emailStudentButton = new JButton();
      emailStudentButton.setBackground(new Color(-44282));
      emailStudentButton.setFont(new Font(emailStudentButton.getFont().getName(), Font.BOLD, 16));
      emailStudentButton.setText("Email Student");
      studentInfoPanel.add(emailStudentButton, new com.intellij.uiDesigner.core.GridConstraints(8, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
   }

   /**
    * @noinspection ALL
    */
   public JComponent $$$getRootComponent$$$() {
      return studentInfoPanel;
   }
}
