package com.arcologydesigns.Views;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by bss64 on 7/14/2015.
 * edited by arnissim on 7/28/2015
 * Some UI elements were generated using the IntelliJ GUI Designer (generated code is available in this class).
 */

public class UserInfoForm extends JDialog {
   private JPanel userInfoPanel;
   private JLabel userNameLabel;
   private JLabel userPhone;
   private JLabel userID;
   private JLabel userAddress;
   private JLabel userEmail;
   private JButton emailUserButton;

   public UserInfoForm() {
      createGUI();
      setActionListeners();
   }

   private void createGUI() {
      // Set title and default close operation
      setTitle("user Information");
      setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);


      // Add the panels to the JFrame
      add(userInfoPanel);

      // Set the size of the JFrame and make it visible
      setSize(600, 400);
      setVisible(true);
   }

   private void setActionListeners() {
      emailUserButton.addActionListener(new ActionListener() {
         @Override
         public void actionPerformed(ActionEvent e) {
            EmailForm emailuserForm = new EmailForm("Email " + getUserNameLabel());
            emailuserForm.setToText(getUserEmail());

         }
      });
   }

   public void setUserNameLabel(String userNameLabel) {
      this.userNameLabel.setText(userNameLabel);
   }

   public void setUserPhone(String userPhone) {
      this.userPhone.setText(userPhone);
   }

   public void setUserID(String userID) {
      this.userID.setText(userID);
   }

   public void setUserAddress(String userAddress) {
      this.userAddress.setText(userAddress);
   }

   public void setUserEmail(String userEmail) {
      this.userEmail.setText(userEmail);
   }

   public String getUserEmail() {
      return userEmail.getText();
   }

   public String getUserAddress() {
      return userAddress.getText();
   }

   public String getUserID() {
      return userID.getText();
   }

   public String getUserPhone() {
      return userPhone.getText();
   }

   public String getUserNameLabel() {
      return userNameLabel.getText();
   }

   {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
      $$$setupUI$$$();
   }

   /**
    * Method generated by IntelliJ IDEA GUI Designer
    * >>> IMPORTANT!! <<<
    * DO NOT edit this method OR call it in your code!
    *
    * @noinspection ALL
    */
   private void $$$setupUI$$$() {
      userInfoPanel = new JPanel();
      userInfoPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(10, 8, new Insets(0, 0, 0, 0), -1, -1));
      userInfoPanel.setBackground(new Color(-14596236));
      userInfoPanel.setFont(new Font(userInfoPanel.getFont().getName(), Font.BOLD, 18));
      userInfoPanel.setForeground(new Color(-1));
      final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
      userInfoPanel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 5, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
      final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
      userInfoPanel.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 8, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      final com.intellij.uiDesigner.core.Spacer spacer3 = new com.intellij.uiDesigner.core.Spacer();
      userInfoPanel.add(spacer3, new com.intellij.uiDesigner.core.GridConstraints(9, 2, 1, 5, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
      final com.intellij.uiDesigner.core.Spacer spacer4 = new com.intellij.uiDesigner.core.Spacer();
      userInfoPanel.add(spacer4, new com.intellij.uiDesigner.core.GridConstraints(1, 7, 8, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      userNameLabel = new JLabel();
      userNameLabel.setBackground(new Color(-1));
      userNameLabel.setFont(new Font(userNameLabel.getFont().getName(), Font.BOLD, 24));
      userNameLabel.setForeground(new Color(-1));
      userNameLabel.setText("User Name");
      userInfoPanel.add(userNameLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 1, 5, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      userAddress = new JLabel();
      userAddress.setBackground(new Color(-1));
      userAddress.setFont(new Font(userAddress.getFont().getName(), Font.BOLD, 18));
      userAddress.setForeground(new Color(-1));
      userAddress.setText("UserAddress");
      userInfoPanel.add(userAddress, new com.intellij.uiDesigner.core.GridConstraints(5, 2, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final com.intellij.uiDesigner.core.Spacer spacer5 = new com.intellij.uiDesigner.core.Spacer();
      userInfoPanel.add(spacer5, new com.intellij.uiDesigner.core.GridConstraints(7, 2, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      userID = new JLabel();
      userID.setBackground(new Color(-1));
      userID.setFont(new Font(userID.getFont().getName(), Font.BOLD, 18));
      userID.setForeground(new Color(-1));
      userID.setText("userID");
      userInfoPanel.add(userID, new com.intellij.uiDesigner.core.GridConstraints(3, 2, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      userPhone = new JLabel();
      userPhone.setBackground(new Color(-1));
      userPhone.setFont(new Font(userPhone.getFont().getName(), Font.BOLD, 18));
      userPhone.setForeground(new Color(-1));
      userPhone.setText("UserPhone");
      userInfoPanel.add(userPhone, new com.intellij.uiDesigner.core.GridConstraints(4, 2, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      userEmail = new JLabel();
      userEmail.setBackground(new Color(-1));
      userEmail.setFont(new Font(userEmail.getFont().getName(), Font.BOLD, 18));
      userEmail.setForeground(new Color(-1));
      userEmail.setText("UserEmail");
      userInfoPanel.add(userEmail, new com.intellij.uiDesigner.core.GridConstraints(6, 2, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final com.intellij.uiDesigner.core.Spacer spacer6 = new com.intellij.uiDesigner.core.Spacer();
      userInfoPanel.add(spacer6, new com.intellij.uiDesigner.core.GridConstraints(2, 2, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      final JLabel label1 = new JLabel();
      label1.setFont(new Font(label1.getFont().getName(), label1.getFont().getStyle(), 14));
      label1.setForeground(new Color(-1));
      label1.setText("Student ID: ");
      userInfoPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final JLabel label2 = new JLabel();
      label2.setFont(new Font(label2.getFont().getName(), label2.getFont().getStyle(), 14));
      label2.setForeground(new Color(-1));
      label2.setText("Phone: ");
      userInfoPanel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final JLabel label3 = new JLabel();
      label3.setFont(new Font(label3.getFont().getName(), label3.getFont().getStyle(), 14));
      label3.setForeground(new Color(-1));
      label3.setText("Mailing Address: ");
      userInfoPanel.add(label3, new com.intellij.uiDesigner.core.GridConstraints(5, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final JLabel label4 = new JLabel();
      label4.setFont(new Font(label4.getFont().getName(), label4.getFont().getStyle(), 14));
      label4.setForeground(new Color(-1));
      label4.setText("Email:");
      userInfoPanel.add(label4, new com.intellij.uiDesigner.core.GridConstraints(6, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      emailUserButton = new JButton();
      emailUserButton.setBackground(new Color(-44282));
      emailUserButton.setFont(new Font(emailUserButton.getFont().getName(), Font.BOLD, 16));
      emailUserButton.setText("Email User");
      userInfoPanel.add(emailUserButton, new com.intellij.uiDesigner.core.GridConstraints(8, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
   }

   /**
    * @noinspection ALL
    */
   public JComponent $$$getRootComponent$$$() {
      return userInfoPanel;
   }
}